- name: Setup Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install Galaxy general collection
  ansible.builtin.shell: ansible-galaxy collection install community.general
  when: APP_TYPE == "nodejs"
  become_user: roboshop

- name: Install Galaxy MongoDB collection
  ansible.builtin.shell: ansible-galaxy collection install community.mongodb
  when: APP_TYPE == "database"
  become_user: roboshop


