- name: Install PIP Modules
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3

- name: Copy {{COMPONENT}} SystemD file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Include Filebeat Installation
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
